<style>
	.c3 {
		font-size: 1.7rem;
	}
</style>

	<h1>PRIVACY POLICY</h1>
	<p class="c25"><span class="c27 c29">&nbsp;</span></p>
	<p class="c25"><span class="c1">Effective date: 05/04/2020</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0 start" start="1">
		<li class="c3"><span class="c18">Introduction</span></li>
	</ol>
	<p class="c7 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">Welcome to&nbsp;</span><span class="c6">BlockVigil, Inc.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">BlockVigil, Inc.&nbsp;(“us”, “we”, or “our”) operates&nbsp;https://tutorials.ethvigil.com&nbsp;(hereinafter referred to as “</span><span class="c6">Service</span><span class="c1">”).</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">Our Privacy Policy governs your visit to&nbsp;https://tutorials.ethvigil.com, and explains how we collect, safeguard and disclose information that results from your use of our Service. </span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">Our Terms and Conditions (“</span><span class="c6">Terms</span><span class="c1">”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“</span><span class="c6">agreement</span><span class="c1">”).</span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="2">
		<li class="c3"><span class="c18">Definitions</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c6">SERVICE&nbsp;</span><span class="c1">means the&nbsp;https://tutorials.ethvigil.com website&nbsp;operated by&nbsp;BlockVigil, Inc.</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c6">PERSONAL DATA</span><span class="c1">&nbsp;means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c6">USAGE DATA</span><span class="c1">&nbsp;is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c6">COOKIES</span><span class="c1">&nbsp;are small files stored on your device (computer or mobile device).</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c6">DATA CONTROLLER</span><span class="c1">&nbsp;means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14"><span class="c24">DATA PROCESSORS (OR SERVICE PROVIDERS)</span><span class="c1">&nbsp;means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14"><span class="c24">DATA SUBJECT&nbsp;</span><span class="c1">is any living individual who is the subject of Personal Data.</span></p>
	<p class="c7 c14"><span class="c15">&nbsp;</span></p>
	<p class="c7 c14"><span class="c24">THE USER&nbsp;</span><span class="c1">is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="3">
		<li class="c3"><span class="c18">Information Collection and Use</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">We collect several different types of information for various purposes to provide and improve our Service to you.</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="4">
		<li class="c3"><span class="c18">Types of Data Collected</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5 c8"><span class="c6">Personal Data</span></p>
	<p class="c5 c8"><span class="c1">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“</span><span class="c6">Personal Data</span><span class="c1">”). Personally identifiable information may include, but is not limited to:</span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_26-1 start" start="1">
		<li class="c7 c17"><span class="c1">Email address</span></li>
	</ol>
	<p class="c7 c20"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us&nbsp;by following the unsubscribe link.</span></p>
	<p class="c7 c32"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c6">Usage Data</span></p>
	<p class="c5"><span class="c1">We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“</span><span class="c6">Usage Data</span><span class="c1">”).</span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</span></p>
	<p class="c7 c32"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c6">Tracking Cookies Data</span></p>
	<p class="c5"><span class="c1">We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">Examples of Cookies we use:</span></p>
	<p class="c5 c8"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-1 start" start="1">
		<li class="c7 c17"><span class="c6">Session Cookies:</span><span class="c1">&nbsp;We use Session Cookies to operate our Service.</span></li>
	</ol>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-1" start="2">
		<li class="c7 c17"><span class="c6">Preference Cookies:</span><span class="c1">&nbsp;We use Preference Cookies to remember your preferences and various settings.</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-1" start="3">
		<li class="c7 c17"><span class="c6">Security Cookies:</span><span class="c1">&nbsp;We use Security Cookies for security purposes.</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-1" start="4">
		<li class="c7 c17"><span class="c6">Advertising Cookies:</span><span class="c1">&nbsp;Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</span></li>
	</ol>
	<p class="c7 c20"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="5">
		<li class="c3"><span class="c18">Use of Data</span></li>
	</ol>
	<p class="c7 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">BlockVigil, Inc.&nbsp;uses the collected data for various purposes:</span></p>
	<p class="c7 c8"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1 start" start="1">
		<li class="c7 c17"><span class="c1">to provide and maintain our Service;</span></li>
	</ol>
	<p class="c7 c20"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="2">
		<li class="c7 c17"><span class="c1">to notify you about changes to our Service; </span></li>
	</ol>
	<p class="c7 c20"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="3">
		<li class="c7 c17"><span class="c1">to allow you to participate in interactive features of our Service when you choose to do so; </span></li>
	</ol>
	<p class="c7 c20"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="4">
		<li class="c7 c17"><span class="c1">to provide customer support; </span></li>
	</ol>
	<p class="c7 c20"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="5">
		<li class="c7 c17"><span class="c1">to gather analysis or valuable information so that we can improve our Service; </span></li>
	</ol>
	<p class="c7 c20"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="6">
		<li class="c7 c17"><span class="c1">to monitor the usage of our Service;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="7">
		<li class="c7 c17"><span class="c1">to detect, prevent and address technical issues;</span></li>
	</ol>
	<p class="c7 c20"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="8">
		<li class="c7 c17"><span class="c1">to fulfill any other purpose for which you provide it;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="9">
		<li class="c7 c17"><span class="c1">to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="10">
		<li class="c7 c17"><span class="c1">to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="11">
		<li class="c7 c17"><span class="c1">to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="12">
		<li class="c7 c17"><span class="c1">in any other way we may describe when you provide the information;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_28-1" start="13">
		<li class="c7 c17"><span class="c1">for any other purpose with your consent. </span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="6">
		<li class="c3"><span class="c18">Retention of Data</span></li>
	</ol>
	<p class="c7 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="7">
		<li class="c3"><span class="c18">Transfer of Data</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5 c26"><span class="c1">BlockVigil, Inc.&nbsp;will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="8">
		<li class="c3"><span class="c18">Disclosure of Data</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">We may disclose personal information that we collect, or you provide:</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-1 start" start="1">
		<li class="c7 c17 c8"><span class="c6">Disclosure for Law Enforcement.</span></li>
	</ol>
	<p class="c7 c11"><span class="c1">Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</span></p>
	<p class="c25 c33"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-1" start="2">
		<li class="c7 c17 c8"><span class="c6">Business Transaction.</span></li>
	</ol>
	<p class="c7 c11"><span class="c1">If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</span></p>
	<p class="c25 c30"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-1" start="3">
		<li class="c7 c8 c10"><span class="c6">Other cases. We may disclose your information also:</span></li>
	</ol>
	<p class="c7 c23 c8"><span class="c6">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-2 start" start="1">
		<li class="c7 c13"><span class="c1">to our subsidiaries and affiliates;</span></li>
	</ol>
	<p class="c0"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-2" start="2">
		<li class="c7 c13"><span class="c1">to contractors, service providers, and other third parties we use to support our business;</span></li>
	</ol>
	<p class="c0"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-2" start="3">
		<li class="c7 c13"><span class="c1">to fulfill the purpose for which you provide it;</span></li>
	</ol>
	<p class="c0"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-2" start="4">
		<li class="c7 c13"><span class="c1">for the purpose of including your company’s logo on our website;</span></li>
	</ol>
	<p class="c0"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-2" start="5">
		<li class="c7 c13"><span class="c1">for any other purpose disclosed by us when you provide the information;</span></li>
	</ol>
	<p class="c0"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-2" start="6">
		<li class="c7 c13"><span class="c1">with your consent in any other cases;</span></li>
	</ol>
	<p class="c0"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_29-2" start="7">
		<li class="c7 c13"><span class="c1">if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</span></li>
	</ol>
	<p class="c0"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="9">
		<li class="c3"><span class="c18">Security of Data</span></li>
	</ol>
	<p class="c7 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="10">
		<li class="c3"><span class="c18">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at </span><span class="c12 c27"><a class="c16" target="_blank" href="https://eur-lex.europa.eu/eli/reg/2016/679/oj">https://eur-lex.europa.eu/eli/reg/2016/679/oj</a></span><span class="c1">&nbsp; </span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at hello@blockvigil.com. </span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">In certain circumstances, you have the following data protection rights:</span></p>
	<p class="c5 c8"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_30-1 start" start="1">
		<li class="c7 c17"><span class="c1">the right to access, update or to delete the information we have on you;</span></li>
	</ol>
	<p class="c7 c11"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_30-1" start="2">
		<li class="c7 c17"><span class="c1">the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_30-1" start="3">
		<li class="c7 c17"><span class="c1">the right to object. You have the right to object to our processing of your Personal Data;</span></li>
	</ol>
	<p class="c7 c11"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_30-1" start="4">
		<li class="c7 c17"><span class="c1">the right of restriction. You have the right to request that we restrict the processing of your personal information;</span></li>
	</ol>
	<p class="c7 c11"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_30-1" start="5">
		<li class="c7 c17"><span class="c1">the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_30-1" start="6">
		<li class="c7 c17"><span class="c1">the right to withdraw consent.&nbsp;You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.</span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="11">
		<li class="c3"><span class="c18">Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at: </span><span class="c12 c27"><a class="c16" target="_blank" href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3">https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/</a></span><span class="c15">&nbsp;</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">According to CalOPPA we agree to the following:</span></p>
	<p class="c7 c8"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_31-1 start" start="1">
		<li class="c7 c17"><span class="c1">users can visit our site anonymously;</span></li>
	</ol>
	<p class="c7 c11"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_31-1" start="2">
		<li class="c7 c17"><span class="c1">our Privacy Policy link includes the word “Privacy”, and can easily be found on the page specified above on the home page of our website;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_31-1" start="3">
		<li class="c7 c17"><span class="c1">users will be notified of any privacy policy changes on our Privacy Policy Page;</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_31-1" start="4">
		<li class="c7 c17"><span class="c1">users are able to change their personal information by emailing us at hello@blockvigil.com. </span></li>
	</ol>
	<p class="c7 c20"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">Our Policy on “Do Not Track” Signals:</span></p>
	<p class="c7 c8"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked. </span></p>
	<p class="c7 c8"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="12">
		<li class="c3"><span class="c18">Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:</span></p>
	<p class="c5 c8"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_33-1 start" start="1">
		<li class="c7 c17"><span class="c6">What personal information we have about you</span><span class="c1">. If you make this request, we will return to you:</span></li>
	</ol>
	<p class="c7 c11"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_34-2 start" start="1">
		<li class="c7 c13"><span class="c1">The categories of personal information we have collected about you.</span></li>
	</ol>
	<p class="c0"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_34-2" start="2">
		<li class="c7 c13"><span class="c1">The categories of sources from which we collect your personal information.</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_34-2" start="3">
		<li class="c7 c13"><span class="c1">The business or commercial purpose for collecting or selling your personal information.</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_34-2" start="4">
		<li class="c7 c13"><span class="c1">The categories of third parties with whom we share personal information.</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_34-2" start="5">
		<li class="c7 c13"><span class="c1">The specific pieces of personal information we have collected about you.</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_34-2" start="6">
		<li class="c7 c13"><span class="c1">A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_34-2" start="7">
		<li class="c7 c13"><span class="c1">A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</span></li>
	</ol>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<p class="c7 c23"><span class="c1">Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12&nbsp;months.</span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_33-1" start="2">
		<li class="c7 c17"><span class="c6">To delete your personal information</span><span class="c1">. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.</span><span class="c6">&nbsp;</span></li>
	</ol>
	<p class="c7 c11"><span class="c6">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_33-1" start="3">
		<li class="c7 c17" id="h.gjdgxs"><span class="c6">To stop selling your personal information</span><span class="c1">. We don't sell or rent your personal information to any third parties for any purpose. You are the only owner of your Personal Data and can request disclosure or deletion at any time.</span></li>
	</ol>
	<p class="c7 c23"><span class="c1">&nbsp;</span></p>
	<p class="c7 c23"><span class="c1">Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.</span></p>
	<p class="c7 c23"><span class="c1">&nbsp;</span></p>
	<p class="c7 c23"><span class="c1">To exercise your California data protection rights described above, please send your request(s) by one of the following means:</span></p>
	<p class="c7 c23"><span class="c1">&nbsp;</span></p>
	<p class="c7 c19"><span class="c1">By email: hello@blockvigil.com</span></p>
	<p class="c7 c19"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020. </span></p>
	<p class="c5 c8"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="13">
		<li class="c3"><span class="c18">Service Providers</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">We may employ third party companies and individuals to facilitate our Service (“</span><span class="c6">Service Providers</span><span class="c1">”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="14">
		<li class="c3"><span class="c18">Analytics</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">We may use third-party Service Providers to monitor and analyze the use of our Service.</span></p>
	<p class="c7 c8"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14 c8 subtitle"><span class="c6">Google Analytics</span></p>
	<p class="c5"><span class="c1">Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: </span><span class="c12 c27"><a class="c16" target="_blank" href="https://policies.google.com/privacy?hl%3Den">https://policies.google.com/privacy?hl=en</a></span><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c9">&nbsp;</span></p>
	<p class="c5"><span class="c1">We also encourage you to review the Google's policy for safeguarding your data: </span><span class="c12 c27"><a class="c16" target="_blank" href="https://support.google.com/analytics/answer/6004245">https://support.google.com/analytics/answer/6004245</a></span><span class="c1">. </span></p>
	<p class="c0"><span class="c2">&nbsp;</span></p>
	<p class="c0 c15"><span class="c1 c9 c19">Fullstory</span></p>
	<p class="c0"><span class="c10">Fullstory analytics is a web analytics service operated by FullStory, Inc. Read the Privacy Policy here: </span><span class="c10 c21"><a class="c18" target="_blank" href="https://www.fullstory.com/legal/privacy/">https://www.fullstory.com/legal/privacy/</a></span><span class="c10">&nbsp;</span></p>
	<p class="c0"><span class="c2">&nbsp;</span></p>
	<p class="c5 c8"><span class="c6">Cloudflare analytics</span></p>
	<p class="c7 c14"><span class="c15">Cloudflare analytics is a web analytics service operated by Cloudflare Inc. Read the Privacy Policy here: </span><span class="c12"><a class="c16" target="_blank" href="https://www.cloudflare.com/privacypolicy">https://www.cloudflare.com/privacypolicy</a></span><span class="c15">&nbsp;</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="15">
		<li class="c3"><span class="c18">CI/CD tools</span></li>
	</ol>
	<p class="c5 c8"><span class="c1">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">We may use third-party Service Providers to automate the development process of our Service. </span></p>
	<p class="c5 c8"><span class="c6">&nbsp;</span></p>
	<p class="c5 c8"><span class="c6">GitHub</span></p>
	<p class="c5 c8"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">GitHub is provided by GitHub, Inc.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">GitHub is a development platform to host and review code, manage projects, and build software.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">For more information on what data GitHub collects for what purpose and how the protection of the data is ensured, please visit GitHub Privacy Policy page:</span><span class="c9">&nbsp;</span><span class="c9"><a class="c16" target="_blank" href="https://help.github.com/en/articles/github-privacy-statement">https://help.github.com/en/articles/github-privacy-statement.</a></span></p>
	<p class="c5 c8"><span class="c6">&nbsp;</span></p>
	<p class="c5 c8"><span class="c6">GitLab CI/CD</span></p>
	<p class="c5 c8"><span class="c6">&nbsp;</span></p>
	<p class="c5"><span class="c1">GitLab CI/CD is provided by GitLab, Inc.</span></p>
	<p class="c5"><span class="c6">&nbsp;</span></p>
	<p class="c5"><span class="c1">GitLab CI (Continuous Integration) service is a part of GitLab that build and test the software whenever developer pushes code to application. </span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">GitLab CD (Continuous Deployment) is a software service that places the changes of every code in the production which results in every day deployment of production. </span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">For more information on what data GitLab CI/CD collects for what purpose and how the protection of the data is ensured, please visit GitLab CI/CD Privacy Policy page: </span><span class="c12 c27"><a class="c16" target="_blank" href="https://about.gitlab.com/privacy/">https://about.gitlab.com/privacy/</a></span><span class="c1">. </span></p>
	<p class="c5 c8"><span class="c6">&nbsp;</span></p>
	<p class="c5 c8"><span class="c6">Travis CI</span></p>
	<p class="c5 c8"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">Travis CI is a distributed continuous integration service to build and test projects hosted at GitHub.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">For more information on what data Travis CI collects for what purpose and how the protection of the data is ensured, please visit Travis CI Privacy Policy page: </span><span class="c12 c27"><a class="c16" target="_blank" href="https://docs.travis-ci.com/legal/privacy-policy">https://docs.travis-ci.com/legal/privacy-policy</a></span><span class="c1">. </span></p>
	<p class="c25"><span class="c6 c35">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="16">
		<li class="c3"><span class="c18">Behavioral Remarketing</span></li>
	</ol>
	<p class="c7 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">BlockVigil, Inc.&nbsp;uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14 c8 subtitle"><span class="c6">Google Ads (AdWords)</span></p>
	<p class="c7 c14"><span class="c1">Google Ads (AdWords) remarketing service is provided by Google Inc.</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15">You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: </span><span class="c12"><a class="c16" target="_blank" href="http://www.google.com/settings/ads">http://www.google.com/settings/ads</a></span><span class="c15">&nbsp;</span></p>
	<p class="c7 c14"><span class="c21 c15">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15">Google also recommends installing the Google Analytics Opt-out Browser Add-on – </span><span class="c12"><a class="c16" target="_blank" href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a></span><span class="c1">&nbsp; – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15">For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: </span><span class="c12"><a class="c16" target="_blank" href="https://policies.google.com/privacy?hl%3Den">https://policies.google.com/privacy?hl=en</a></span><span class="c1">&nbsp;</span></p>
	<p class="c7 c14 subtitle"><span class="c6">&nbsp;</span></p>
	<p class="c7 c14 c8 subtitle"><span class="c6">Twitter</span></p>
	<p class="c7 c14"><span class="c1">Twitter remarketing service is provided by Twitter Inc.</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15">You can opt-out from Twitter's interest-based ads by following their instructions: </span><span class="c12"><a class="c16" target="_blank" href="https://support.twitter.com/articles/20170405">https://support.twitter.com/articles/20170405</a></span><span class="c15">&nbsp;</span></p>
	<p class="c7 c14"><span class="c21 c15">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15">You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page: </span><span class="c12"><a class="c16" target="_blank" href="https://twitter.com/privacy">https://twitter.com/privacy</a></span><span class="c1">&nbsp;</span></p>
	<p class="c7 c14 subtitle"><span class="c6">&nbsp;</span></p>
	<p class="c7 c14 c8 subtitle"><span class="c6">Facebook</span></p>
	<p class="c7 c14"><span class="c1">Facebook remarketing service is provided by Facebook Inc.</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15">You can learn more about interest-based advertising from Facebook by visiting this page: </span><span class="c12"><a class="c16" target="_blank" href="https://www.facebook.com/help/164968693837950">https://www.facebook.com/help/164968693837950</a></span><span class="c15">&nbsp;</span></p>
	<p class="c7 c14"><span class="c21 c15">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15">To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: </span><span class="c12"><a class="c16" target="_blank" href="https://www.facebook.com/help/568137493302217">https://www.facebook.com/help/568137493302217</a></span><span class="c15">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15 c21">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15">Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA </span><span class="c12"><a class="c16" target="_blank" href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a></span><span class="c15">, the Digital Advertising Alliance of Canada in Canada </span><span class="c12"><a class="c16" target="_blank" href="http://youradchoices.ca">http://youradchoices.ca/</a></span><span class="c15">&nbsp;or the European Interactive Digital Advertising Alliance in Europe </span><span class="c12"><a class="c16" target="_blank" href="http://www.youronlinechoices.eu">http://www.youronlinechoices.eu/</a></span><span class="c1">&nbsp;, or opt-out using your mobile device settings.</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14"><span class="c15">For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: </span><span class="c12"><a class="c16" target="_blank" href="https://www.facebook.com/privacy/explanation">https://www.facebook.com/privacy/explanation</a></span><span class="c15">&nbsp;</span></p>
	<p class="c7 c14 subtitle"><span class="c6">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="17">
		<li class="c3"><span class="c18">Payments</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).</span></p>
	<p class="c5"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14"><span class="c1">We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</span></p>
	<p class="c7 c14"><span class="c1">&nbsp;</span></p>
	<p class="c7 c14 c8"><span class="c1">The payment processors we work with are:</span></p>
	<p class="c25 c14"><span class="c1">&nbsp;</span></p>
	<p class="c25 c14 c8 subtitle"><span class="c6">Stripe:</span></p>
	<p class="c25 c14"><span class="c15">Their Privacy Policy can be viewed at: </span><span class="c12"><a class="c16" target="_blank" href="https://stripe.com/us/privacy">https://stripe.com/us/privacy</a></span><span class="c1">&nbsp;</span></p>
	<p class="c4"><span class="c6">&nbsp;</span></p>
	<p class="c4"><span class="c6">Plaid:</span></p>
	<p class="c7 c20 c8"><span class="c15">Their End User Privacy Policy, Cookie Policy and Privacy Statement can be viewed at </span><span class="c12"><a class="c16" target="_blank" href="https://plaid.com/legal">https://plaid.com/legal/</a></span><span class="c1">. </span></p>
	<p class="c25 c14"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="18">
		<li class="c3"><span class="c18">Links to Other Sites</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</span></p>
	<p class="c7"><span class="c18">&nbsp;</span></p>
	<p class="c7 c14"><span class="c1">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</span></p>
	<p class="c25 c14"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="19">
		<li class="c3"><span class="c18">Children's Privacy</span></li>
	</ol>
	<p class="c7 c20 c8"><span class="c1">&nbsp;</span></p>
	<p class="c7 c20 c8"><span class="c15">Our Services are not intended for use by children under the age of 13 (“</span><span class="c24">Children</span><span class="c1">”). </span></p>
	<p class="c7 c20 c8"><span class="c1">&nbsp;</span></p>
	<p class="c7 c20 c8"><span class="c1">We do not knowingly collect personally identifiable information from Children under 13. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that ce have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</span></p>
	<p class="c5 c8"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="20">
		<li class="c3"><span class="c18">Changes to This Privacy Policy</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</span></p>
	<p class="c7"><span class="c18">&nbsp;</span></p>
	<p class="c5"><span class="c1">We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.</span></p>
	<p class="c7"><span class="c1">&nbsp;</span></p>
	<p class="c5"><span class="c1">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</span></p>
	<p class="c25"><span class="c1">&nbsp;</span></p>
	<ol class="c2 lst-kix_list_27-0" start="21">
		<li class="c3"><span class="c18">Contact Us</span></li>
	</ol>
	<p class="c5 c8"><span class="c18">&nbsp;</span></p>
	<p class="c5 c8"><span class="c1">If you have any questions about this Privacy Policy, please contact us:</span></p>
	<p class="c5 c8"><span class="c1">&nbsp;</span></p>
	<p class="c25 c14"><span class="c1">By email: hello@blockvigil.com.</span></p>
	<p class="c25 c14"><span class="c1">&nbsp;</span></p>
